/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    ventures: Venture;
    myinsights: Myinsight;
    'case-studies': CaseStudy;
    challenge: Challenge;
    hero: Hero;
    industries: Industry;
    response: Response;
    response_card: ResponseCard;
    approach: Approach;
    standards: Standard;
    application: Application;
    about: About;
    cta: Cta;
    'executive-profile': ExecutiveProfile;
    perspective: Perspective;
    impact: Impact;
    focus: Focus;
    faq: Faq;
    'leadership-papers': LeadershipPaper;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    ventures: VenturesSelect<false> | VenturesSelect<true>;
    myinsights: MyinsightsSelect<false> | MyinsightsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    challenge: ChallengeSelect<false> | ChallengeSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    response: ResponseSelect<false> | ResponseSelect<true>;
    response_card: ResponseCardSelect<false> | ResponseCardSelect<true>;
    approach: ApproachSelect<false> | ApproachSelect<true>;
    standards: StandardsSelect<false> | StandardsSelect<true>;
    application: ApplicationSelect<false> | ApplicationSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
    'executive-profile': ExecutiveProfileSelect<false> | ExecutiveProfileSelect<true>;
    perspective: PerspectiveSelect<false> | PerspectiveSelect<true>;
    impact: ImpactSelect<false> | ImpactSelect<true>;
    focus: FocusSelect<false> | FocusSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'leadership-papers': LeadershipPapersSelect<false> | LeadershipPapersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ventures".
 */
export interface Venture {
  id: number;
  title: string;
  /**
   * Auto-filled from title. You can override it manually.
   */
  slug?: string | null;
  /**
   * Upload or select image.
   */
  img: number | Media;
  status: 'Exploring' | 'Active' | 'Relaunching';
  /**
   * Short intro shown in the hero section of the detail page.
   */
  shortOverview?: string | null;
  /**
   * First sentence is also used as the card summary on the index page.
   */
  ventureOverview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  problemSpace?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  innovationDirection?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dataAnalytics?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select the type of collaboration being sought.
   */
  collaborationSought?: ('research-partners' | 'platform-integration' | 'regulated-pilots')[] | null;
  /**
   * Mark as a Featured Article.
   */
  featured?: boolean | null;
  /**
   * Overrides the page title in search engine results. Leave blank to use the article title.
   */
  seoTitle?: string | null;
  /**
   * Short description for search engine results.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "myinsights".
 */
export interface Myinsight {
  id: number;
  title: string;
  /**
   * Auto-filled from title. You can override it manually.
   */
  slug: string;
  category:
    | 'Governance & Compliance'
    | 'Research Collaboration'
    | 'Interoperability & Standards'
    | 'Preventive Health Innovation'
    | 'AI & Regulated Data';
  /**
   * Featured image.
   */
  img: number | Media;
  /**
   * Publication date.
   */
  date?: string | null;
  /**
   * Short summary shown in the hero and on listing cards.
   */
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Mark as a Cornerstone Article.
   */
  flagship?: boolean | null;
  /**
   * Mark as a Featured Article.
   */
  featured?: boolean | null;
  /**
   * Add, reorder, or remove sections freely.
   */
  sections: {
    /**
     * Section heading shown on the page.
     */
    heading: string;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * Overrides the page <title>. Leave blank to use the article title.
   */
  seoTitle?: string | null;
  /**
   * Short description for search engine results.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * e.g. "Research Collaboration / TRE"
   */
  theme: string;
  /**
   * Display date e.g. "March 2024"
   */
  date?: string | null;
  /**
   * Fallback period label if no date e.g. "Q1 2024"
   */
  period?: string | null;
  image: number | Media;
  /**
   * Add, reorder, or remove sections freely.
   */
  sections?:
    | {
        /**
         * Section heading shown on the page.
         */
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge".
 */
export interface Challenge {
  id: number;
  /**
   * Small badge label above the heading (e.g. "Infrastructure").
   */
  badge?: string | null;
  /**
   * First line of the heading (rendered in lime).
   */
  heading: string;
  /**
   * Second line of the heading (rendered in white, lighter weight).
   */
  headingLight?: string | null;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image shown below the body text.
   */
  image: number | Media;
  /**
   * Optional caption beneath the image.
   */
  imageCaption?: string | null;
  /**
   * Cards shown in the right column.
   */
  cards?:
    | {
        title: string;
        /**
         * Short descriptor line shown beneath the title.
         */
        body: string;
        /**
         * Pick the icon that best represents this card.
         */
        icon?:
          | ('fragmented' | 'server' | 'network' | 'shieldCheck' | 'shield' | 'layers' | 'activity' | 'globe')
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Main hero heading. The highlighted portion is set separately.
   */
  heading: string;
  /**
   * Portion of the heading rendered in lime (#c5f018). Must match a substring of Heading (e.g. Jason with Sturdy in white).
   */
  headingHighlight?: string | null;
  /**
   * Large line shown beneath the main heading.
   */
  subheading: string;
  /**
   * Dot-separated disciplines line beneath the subheading.
   */
  tagline?: string | null;
  /**
   * Add content sections to the hero. Each section has its own type and position slot.
   */
  sections?:
    | (
        | {
            /**
             * Where this section renders in the hero layout.
             */
            position:
              | 'above-heading'
              | 'below-heading'
              | 'below-subheading'
              | 'below-tagline'
              | 'above-cta'
              | 'below-cta';
            /**
             * Supports bold, italic, and inline links.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextSection';
          }
        | {
            /**
             * Where this section renders in the hero layout.
             */
            position:
              | 'above-heading'
              | 'below-heading'
              | 'below-subheading'
              | 'below-tagline'
              | 'above-cta'
              | 'below-cta';
            /**
             * Add and reorder bullet items.
             */
            items: {
              /**
               * Supports bold, italic, and inline links per item.
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'bulletList';
          }
      )[]
    | null;
  /**
   * Text on the primary (lime) button.
   */
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  /**
   * Text on the secondary (outline) button.
   */
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  /**
   * Portrait shown on the right. Leave blank to use the default local image.
   */
  portrait?: (number | null) | Media;
  portraitAlt?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  /**
   * Small badge label shown above the heading (e.g. "Industries").
   */
  sectionLabel?: string | null;
  /**
   * First part of the heading rendered in normal white text.
   */
  headingRegular: string;
  /**
   * Second part of the heading rendered in lime (#c5f018).
   */
  headingAccent: string;
  /**
   * Third / trailing part of the heading rendered in light white text.
   */
  headingLight?: string | null;
  /**
   * Descriptive paragraphs shown beside the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The grid cards shown in the capabilities section (typically 4).
   */
  cards?:
    | {
        /**
         * Card heading (e.g. "Data Governance & Compliance").
         */
        title: string;
        /**
         * Short descriptor line shown beneath the title.
         */
        description: string;
        /**
         * Background image for this card.
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response".
 */
export interface Response {
  id: number;
  /**
   * Small badge label above the heading.
   */
  badge?: string | null;
  /**
   * First line of the heading (rendered in lime).
   */
  heading: string;
  /**
   * Second line of the heading (rendered in white, lighter weight).
   */
  headingLight?: string | null;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Text on the call-to-action button.
   */
  ctaLabel?: string | null;
  /**
   * URL the CTA button links to.
   */
  ctaHref?: string | null;
  /**
   * Up to 3 images shown in the stacked animation on the right.
   */
  images?:
    | {
        image: number | Media;
        /**
         * Alt text for accessibility.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response_card".
 */
export interface ResponseCard {
  id: number;
  /**
   * Display number shown top-left of the card (e.g. "01", "02").
   */
  indexLabel: string;
  /**
   * Card title text.
   */
  title: string;
  /**
   * Short description shown beneath the title.
   */
  body?: string | null;
  /**
   * Number of lime bars shown top-right of the card (1–3).
   */
  bars: '1' | '2' | '3';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach".
 */
export interface Approach {
  id: number;
  /**
   * Internal label to identify this document in the CMS list.
   */
  sectionLabel?: string | null;
  /**
   * Small badge label above the heading (e.g. "Challenge").
   */
  badge?: string | null;
  /**
   * First part of heading rendered in lime (e.g. "How").
   */
  headingAccent?: string | null;
  /**
   * Second part of heading rendered in white (e.g. "I Work").
   */
  heading?: string | null;
  /**
   * Body paragraphs shown below the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  exploreHeading?: string | null;
  exploreBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  exploreCtaLabel?: string | null;
  exploreCtaHref?: string | null;
  exploreCtaLabel2?: string | null;
  exploreCtaHref2?: string | null;
  exploreBackgroundImage?: (number | null) | Media;
  items?:
    | {
        title: string;
        /**
         * Short tagline shown on the card.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        icon: 'trust' | 'control' | 'standards' | 'resilience';
        bars: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standards".
 */
export interface Standard {
  id: number;
  /**
   * Small badge label above the heading (e.g. "Standards").
   */
  badge?: string | null;
  /**
   * First part of heading (rendered in white).
   */
  heading: string;
  /**
   * Second part of heading (rendered in lime).
   */
  headingAccent?: string | null;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The horizontally scrollable focus area cards.
   */
  cards?:
    | {
        /**
         * URL-safe identifier (e.g. "data-protection-privacy").
         */
        slug: string;
        title: string;
        /**
         * Short descriptor shown on card hover.
         */
        tagline: string;
        /**
         * Background image for the card.
         */
        image: number | Media;
        /**
         * Pick the icon that best represents this focus area.
         */
        icon:
          | 'data-governance'
          | 'security-architecture'
          | 'regulatory-systems'
          | 'institutional-infrastructure'
          | 'health'
          | 'research'
          | 'financial'
          | 'european-data';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application".
 */
export interface Application {
  id: number;
  /**
   * Small badge label above the heading (e.g. "Application").
   */
  badge?: string | null;
  /**
   * First part of heading (rendered in white).
   */
  heading: string;
  /**
   * Second part of heading (rendered in lime).
   */
  headingAccent?: string | null;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The application environment cards displayed in the grid.
   */
  cards?:
    | {
        /**
         * URL-safe identifier (e.g. "research-platforms").
         */
        slug: string;
        title: string;
        /**
         * Short descriptor shown beneath the title.
         */
        tagline: string;
        /**
         * Optional image for the card.
         */
        image?: (number | null) | Media;
        /**
         * Pick the icon that best represents this application area.
         */
        icon:
          | 'data-governance'
          | 'security-architecture'
          | 'regulatory-systems'
          | 'institutional-infrastructure'
          | 'health'
          | 'research'
          | 'financial'
          | 'european-data';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Main heading text (e.g. "About").
   */
  heading: string;
  /**
   * Subtitle paragraph shown on the right side.
   */
  subtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: number;
  /**
   * First part of heading (white, light weight).
   */
  headingStart?: string | null;
  /**
   * Middle part of heading (lime, medium weight).
   */
  headingMiddle: string;
  /**
   * Last part of heading (white).
   */
  headingEnd?: string | null;
  /**
   * Paragraph below the heading.
   */
  subheading?: string | null;
  /**
   * CTA button text.
   */
  buttonLabel?: string | null;
  /**
   * CTA button link (e.g. /case-studies).
   */
  buttonHref?: string | null;
  /**
   * Exactly 3 images shown in the fan layout at the bottom.
   */
  cards?:
    | {
        image: number | Media;
        /**
         * Alt text for accessibility.
         */
        alt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executive-profile".
 */
export interface ExecutiveProfile {
  id: number;
  /**
   * First part of the section heading (rendered in lime green).
   */
  sectionHeading?: string | null;
  /**
   * Second part of the section heading (rendered in white).
   */
  sectionHeadingAccent?: string | null;
  /**
   * Each item is one paragraph of body text.
   */
  paragraphs?:
    | {
        text: string;
        /**
         * Renders this paragraph in bold white (for callout lines).
         */
        isBold?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Background image shown on the right side.
   */
  image: number | Media;
  /**
   * Controls display order. Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perspective".
 */
export interface Perspective {
  id: number;
  /**
   * Small badge label above the heading.
   */
  badge?: string | null;
  /**
   * First line of the heading (rendered in lime).
   */
  heading: string;
  /**
   * Second line of the heading (rendered in white, lighter weight).
   */
  headingLight?: string | null;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Text on the primary call-to-action button.
   */
  ctaLabel?: string | null;
  /**
   * URL the primary CTA button links to.
   */
  ctaHref?: string | null;
  /**
   * Text on the secondary call-to-action button.
   */
  ctaLabel2?: string | null;
  /**
   * URL the secondary CTA button links to.
   */
  ctaHref2?: string | null;
  /**
   * Up to 3 images shown in the stacked animation on the right.
   */
  images?:
    | {
        image: number | Media;
        /**
         * Alt text for accessibility.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact".
 */
export interface Impact {
  id: number;
  /**
   * Small badge label above the heading.
   */
  badge?: string | null;
  /**
   * Accent word rendered in lime (e.g. "Why").
   */
  headingAccent: string;
  /**
   * Main heading text rendered in white.
   */
  heading: string;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Main image displayed on the left side of the section.
   */
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "focus".
 */
export interface Focus {
  id: number;
  /**
   * Small badge label above the heading.
   */
  badge?: string | null;
  /**
   * Accent word rendered in lime.
   */
  headingAccent?: string | null;
  /**
   * Main heading text rendered in white.
   */
  heading: string;
  /**
   * Focus area cards (max 6, displayed in 3-column grid).
   */
  cards?:
    | {
        /**
         * Icon displayed at the top of the card.
         */
        icon: 'governance' | 'security' | 'infrastructure' | 'operating' | 'regulatory' | 'collaboration';
        /**
         * Card heading.
         */
        title: string;
        /**
         * Short description shown beneath the card title.
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * The FAQ question text.
   */
  question: string;
  /**
   * The answer to the question.
   */
  answer: string;
  /**
   * Controls display order (ascending). e.g. 1, 2, 3...
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-papers".
 */
export interface LeadershipPaper {
  id: number;
  title: string;
  slug: string;
  subtitle?: string | null;
  /**
   * e.g. "Governance & Compliance"
   */
  category: string;
  /**
   * Display date e.g. "July 1, 2026"
   */
  date?: string | null;
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  flagship?: boolean | null;
  /**
   * Add, reorder, or remove sections freely.
   */
  sections?:
    | {
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'ventures';
        value: number | Venture;
      } | null)
    | ({
        relationTo: 'myinsights';
        value: number | Myinsight;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'challenge';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'hero';
        value: number | Hero;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'response';
        value: number | Response;
      } | null)
    | ({
        relationTo: 'response_card';
        value: number | ResponseCard;
      } | null)
    | ({
        relationTo: 'approach';
        value: number | Approach;
      } | null)
    | ({
        relationTo: 'standards';
        value: number | Standard;
      } | null)
    | ({
        relationTo: 'application';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'about';
        value: number | About;
      } | null)
    | ({
        relationTo: 'cta';
        value: number | Cta;
      } | null)
    | ({
        relationTo: 'executive-profile';
        value: number | ExecutiveProfile;
      } | null)
    | ({
        relationTo: 'perspective';
        value: number | Perspective;
      } | null)
    | ({
        relationTo: 'impact';
        value: number | Impact;
      } | null)
    | ({
        relationTo: 'focus';
        value: number | Focus;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'leadership-papers';
        value: number | LeadershipPaper;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ventures_select".
 */
export interface VenturesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  img?: T;
  status?: T;
  shortOverview?: T;
  ventureOverview?: T;
  problemSpace?: T;
  innovationDirection?: T;
  dataAnalytics?: T;
  collaborationSought?: T;
  featured?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "myinsights_select".
 */
export interface MyinsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  img?: T;
  date?: T;
  summary?: T;
  flagship?: T;
  featured?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  theme?: T;
  date?: T;
  period?: T;
  image?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  featured?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge_select".
 */
export interface ChallengeSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingLight?: T;
  body?: T;
  image?: T;
  imageCaption?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  heading?: T;
  headingHighlight?: T;
  subheading?: T;
  tagline?: T;
  sections?:
    | T
    | {
        richTextSection?:
          | T
          | {
              position?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        bulletList?:
          | T
          | {
              position?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  portrait?: T;
  portraitAlt?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  sectionLabel?: T;
  headingRegular?: T;
  headingAccent?: T;
  headingLight?: T;
  body?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response_select".
 */
export interface ResponseSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingLight?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response_card_select".
 */
export interface ResponseCardSelect<T extends boolean = true> {
  indexLabel?: T;
  title?: T;
  body?: T;
  bars?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach_select".
 */
export interface ApproachSelect<T extends boolean = true> {
  sectionLabel?: T;
  badge?: T;
  headingAccent?: T;
  heading?: T;
  body?: T;
  exploreHeading?: T;
  exploreBody?: T;
  exploreCtaLabel?: T;
  exploreCtaHref?: T;
  exploreCtaLabel2?: T;
  exploreCtaHref2?: T;
  exploreBackgroundImage?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        bars?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standards_select".
 */
export interface StandardsSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  cards?:
    | T
    | {
        slug?: T;
        title?: T;
        tagline?: T;
        image?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application_select".
 */
export interface ApplicationSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  cards?:
    | T
    | {
        slug?: T;
        title?: T;
        tagline?: T;
        image?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  headingStart?: T;
  headingMiddle?: T;
  headingEnd?: T;
  subheading?: T;
  buttonLabel?: T;
  buttonHref?: T;
  cards?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executive-profile_select".
 */
export interface ExecutiveProfileSelect<T extends boolean = true> {
  sectionHeading?: T;
  sectionHeadingAccent?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        isBold?: T;
        id?: T;
      };
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perspective_select".
 */
export interface PerspectiveSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingLight?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  ctaLabel2?: T;
  ctaHref2?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact_select".
 */
export interface ImpactSelect<T extends boolean = true> {
  badge?: T;
  headingAccent?: T;
  heading?: T;
  body?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "focus_select".
 */
export interface FocusSelect<T extends boolean = true> {
  badge?: T;
  headingAccent?: T;
  heading?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-papers_select".
 */
export interface LeadershipPapersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  category?: T;
  date?: T;
  summary?: T;
  image?: T;
  flagship?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline: string;
  copyright: string;
  /**
   * e.g. "Let's Connect". Leave blank to hide the button.
   */
  ctaLabel?: string | null;
  /**
   * e.g. "/contact" or "https://calendly.com/..."
   */
  ctaHref?: string | null;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  copyright?: T;
  ctaLabel?: T;
  ctaHref?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}