/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    ventures: Venture;
    myinsights: Myinsight;
    'case-studies': CaseStudy;
    challenge: Challenge;
    hero: Hero;
    infrastructure: Infrastructure;
    response: Response;
    response_card: ResponseCard;
    principles: Principle;
    standards: Standard;
    cta: Cta;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    ventures: VenturesSelect<false> | VenturesSelect<true>;
    myinsights: MyinsightsSelect<false> | MyinsightsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    challenge: ChallengeSelect<false> | ChallengeSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    infrastructure: InfrastructureSelect<false> | InfrastructureSelect<true>;
    response: ResponseSelect<false> | ResponseSelect<true>;
    response_card: ResponseCardSelect<false> | ResponseCardSelect<true>;
    principles: PrinciplesSelect<false> | PrinciplesSelect<true>;
    standards: StandardsSelect<false> | StandardsSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ventures".
 */
export interface Venture {
  id: number;
  title: string;
  /**
   * Auto-filled from title. You can override it manually.
   */
  slug?: string | null;
  /**
   * Upload or select image.
   */
  img: number | Media;
  status: 'Exploring' | 'Active' | 'Relaunching';
  /**
   * Short intro shown in the hero section of the detail page.
   */
  shortOverview?: string | null;
  /**
   * First sentence is also used as the card summary on the index page.
   */
  ventureOverview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  problemSpace?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  innovationDirection?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dataAnalytics?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select the type of collaboration being sought.
   */
  collaborationSought?: ('research-partners' | 'platform-integration' | 'regulated-pilots')[] | null;
  /**
   * Mark as a Featured Article.
   */
  featured?: boolean | null;
  /**
   * Overrides the page title in search engine results. Leave blank to use the article title.
   */
  seoTitle?: string | null;
  /**
   * Short description for search engine results.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "myinsights".
 */
export interface Myinsight {
  id: number;
  title: string;
  /**
   * Auto-filled from title. You can override it manually.
   */
  slug?: string | null;
  category:
    | 'Governance & Compliance'
    | 'Research Collaboration'
    | 'Interoperability & Standards'
    | 'Preventive Health Innovation'
    | 'AI & Regulated Data';
  author: string;
  /**
   * Upload or select image.
   */
  img: number | Media;
  /**
   * Publication date.
   */
  date?: string | null;
  /**
   * Short summary shown on the listing card.
   */
  excerpt: string;
  /**
   * Mark as a Cornerstone Article.
   */
  flagship?: boolean | null;
  /**
   * Mark as a Featured Article.
   */
  featured?: boolean | null;
  sections: {
    heading: string;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * Overrides the page title in search engine results. Leave blank to use the article title.
   */
  seoTitle?: string | null;
  /**
   * Short description for search engine results.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * Auto-filled from title. You can override it manually.
   */
  slug?: string | null;
  /**
   * Short description shown on listing cards.
   */
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * e.g. "Research Collaboration / TRE"
   */
  theme: string;
  /**
   * e.g. "Multi-institutional research consortium"
   */
  context: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Upload or select image.
   */
  img: number | Media;
  overviewContext?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  environmentModel?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  governanceControls?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  standardsInteroperability?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  outcomesImpact?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  partnershipRelevance?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mark as a Featured Article.
   */
  featured?: boolean | null;
  /**
   * Overrides the page title in search engine results. Leave blank to use the article title.
   */
  seoTitle?: string | null;
  /**
   * Short description for search engine results.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge".
 */
export interface Challenge {
  id: number;
  /**
   * Small label shown next to the green dot (e.g. "Challenge").
   */
  badge: string;
  /**
   * Main section heading. The highlighted (lime) portion is set separately.
   */
  heading: string;
  /**
   * The portion of the heading rendered in lime (#c5f018). Must match a substring of Heading.
   */
  headingHighlight?: string | null;
  /**
   * Short paragraph below the heading (left column).
   */
  intro: string;
  /**
   * The 2×2 grid of expertise cards. Supports up to 4 items.
   */
  expertiseItems?:
    | {
        title: string;
        /**
         * Short supporting sentence shown beneath the title.
         */
        body: string;
        /**
         * Choose the icon to display on this card.
         */
        icon: 'governance' | 'infrastructure' | 'collaboration' | 'interoperability';
        id?: string | null;
      }[]
    | null;
  /**
   * Large image shown in the right column.
   */
  image: number | Media;
  /**
   * Small caption rendered below the image.
   */
  imageCaption?: string | null;
  /**
   * Text on the call-to-action button.
   */
  ctaLabel?: string | null;
  /**
   * Where the CTA button links to.
   */
  ctaHref?: string | null;
  /**
   * Overrides the page <title>. Leave blank to use Heading.
   */
  seoTitle?: string | null;
  /**
   * Short description for search engine results.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Main hero heading. The highlighted portion is set separately.
   */
  heading: string;
  /**
   * Portion of the heading rendered in lime (#c5f018). Must match a substring of Heading.
   */
  headingHighlight?: string | null;
  /**
   * Large line shown beneath the main heading.
   */
  subheading: string;
  /**
   * Dot-separated disciplines line beneath the subheading.
   */
  tagline?: string | null;
  /**
   * Add content sections to the hero. Each section has its own type and position slot.
   */
  sections?:
    | (
        | {
            /**
             * Where this section renders in the hero layout.
             */
            position:
              | 'above-heading'
              | 'below-heading'
              | 'below-subheading'
              | 'below-tagline'
              | 'above-cta'
              | 'below-cta';
            /**
             * Supports bold, italic, and inline links.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextSection';
          }
        | {
            /**
             * Where this section renders in the hero layout.
             */
            position:
              | 'above-heading'
              | 'below-heading'
              | 'below-subheading'
              | 'below-tagline'
              | 'above-cta'
              | 'below-cta';
            /**
             * Add and reorder bullet items.
             */
            items: {
              /**
               * Supports bold, italic, and inline links per item.
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'bulletList';
          }
      )[]
    | null;
  /**
   * Text on the primary (lime) button.
   */
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  /**
   * Text on the secondary (outline) button.
   */
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  /**
   * Portrait shown on the right. Leave blank to use the default local image.
   */
  portrait?: (number | null) | Media;
  portraitAlt?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure".
 */
export interface Infrastructure {
  id: number;
  /**
   * Small badge label above the heading (e.g. "Infrastructure").
   */
  badge?: string | null;
  /**
   * First line of the heading (rendered in lime).
   */
  heading: string;
  /**
   * Second line of the heading (rendered in white, lighter weight).
   */
  headingLight?: string | null;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image shown below the body text.
   */
  image: number | Media;
  imageCaption?: string | null;
  /**
   * The four (or more) cards shown on the right column.
   */
  cards?:
    | {
        title: string;
        /**
         * Short descriptor line shown beneath the title.
         */
        body: string;
        /**
         * Pick the icon that best represents this card.
         */
        icon?: ('shield' | 'layers' | 'activity' | 'globe') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response".
 */
export interface Response {
  id: number;
  /**
   * Small badge label above the heading.
   */
  badge?: string | null;
  /**
   * First line of the heading (rendered in lime).
   */
  heading: string;
  /**
   * Second line of the heading (rendered in white, lighter weight).
   */
  headingLight?: string | null;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Text on the call-to-action button.
   */
  ctaLabel?: string | null;
  /**
   * URL the CTA button links to.
   */
  ctaHref?: string | null;
  /**
   * Up to 3 images shown in the stacked animation on the right.
   */
  images?:
    | {
        image: number | Media;
        /**
         * Alt text for accessibility.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response_card".
 */
export interface ResponseCard {
  id: number;
  /**
   * Display number shown top-left of the card (e.g. "01", "02").
   */
  indexLabel: string;
  /**
   * Card title text.
   */
  title: string;
  /**
   * Short description shown beneath the title.
   */
  body?: string | null;
  /**
   * Number of lime bars shown top-right of the card (1–3).
   */
  bars: '1' | '2' | '3';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles".
 */
export interface Principle {
  id: number;
  /**
   * Internal label to identify this document in the CMS list.
   */
  sectionLabel?: string | null;
  exploreHeading?: string | null;
  exploreBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  exploreCtaLabel?: string | null;
  exploreCtaHref?: string | null;
  exploreBackgroundImage?: (number | null) | Media;
  /**
   * Add, remove, or reorder cards here. Drag rows to reorder.
   */
  items?:
    | {
        /**
         * Card title (e.g. "Trust").
         */
        title: string;
        /**
         * Description shown in the active card.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        icon: 'trust' | 'control' | 'standards' | 'resilience';
        /**
         * Number of lime bars (1–8).
         */
        bars: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standards".
 */
export interface Standard {
  id: number;
  /**
   * Small badge label above the heading (e.g. "Standards").
   */
  badge?: string | null;
  /**
   * Main heading of the section.
   */
  heading: string;
  /**
   * Paragraph text beneath the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The horizontally scrollable focus area cards.
   */
  cards?:
    | {
        /**
         * URL-safe identifier (e.g. "data-protection-privacy").
         */
        slug: string;
        title: string;
        /**
         * Short descriptor shown on card hover.
         */
        tagline: string;
        /**
         * Background image for the card.
         */
        image: number | Media;
        /**
         * Pick the icon that best represents this focus area.
         */
        icon:
          | 'data-governance'
          | 'security-architecture'
          | 'regulatory-systems'
          | 'institutional-infrastructure'
          | 'health'
          | 'research'
          | 'financial'
          | 'european-data';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: number;
  /**
   * First part of heading (white, light weight).
   */
  headingStart?: string | null;
  /**
   * Middle part of heading (lime, medium weight).
   */
  headingMiddle: string;
  /**
   * Last part of heading (white).
   */
  headingEnd?: string | null;
  /**
   * Paragraph below the heading.
   */
  subheading?: string | null;
  /**
   * CTA button text.
   */
  buttonLabel?: string | null;
  /**
   * CTA button link (e.g. /case-studies).
   */
  buttonHref?: string | null;
  /**
   * Exactly 3 images shown in the fan layout at the bottom.
   */
  cards?:
    | {
        image: number | Media;
        /**
         * Alt text for accessibility.
         */
        alt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'ventures';
        value: number | Venture;
      } | null)
    | ({
        relationTo: 'myinsights';
        value: number | Myinsight;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'challenge';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'hero';
        value: number | Hero;
      } | null)
    | ({
        relationTo: 'infrastructure';
        value: number | Infrastructure;
      } | null)
    | ({
        relationTo: 'response';
        value: number | Response;
      } | null)
    | ({
        relationTo: 'response_card';
        value: number | ResponseCard;
      } | null)
    | ({
        relationTo: 'principles';
        value: number | Principle;
      } | null)
    | ({
        relationTo: 'standards';
        value: number | Standard;
      } | null)
    | ({
        relationTo: 'cta';
        value: number | Cta;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ventures_select".
 */
export interface VenturesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  img?: T;
  status?: T;
  shortOverview?: T;
  ventureOverview?: T;
  problemSpace?: T;
  innovationDirection?: T;
  dataAnalytics?: T;
  collaborationSought?: T;
  featured?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "myinsights_select".
 */
export interface MyinsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  author?: T;
  img?: T;
  date?: T;
  excerpt?: T;
  flagship?: T;
  featured?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  theme?: T;
  context?: T;
  img?: T;
  overviewContext?: T;
  environmentModel?: T;
  governanceControls?: T;
  standardsInteroperability?: T;
  outcomesImpact?: T;
  partnershipRelevance?: T;
  featured?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge_select".
 */
export interface ChallengeSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingHighlight?: T;
  intro?: T;
  expertiseItems?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  image?: T;
  imageCaption?: T;
  ctaLabel?: T;
  ctaHref?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  heading?: T;
  headingHighlight?: T;
  subheading?: T;
  tagline?: T;
  sections?:
    | T
    | {
        richTextSection?:
          | T
          | {
              position?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        bulletList?:
          | T
          | {
              position?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  portrait?: T;
  portraitAlt?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure_select".
 */
export interface InfrastructureSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingLight?: T;
  body?: T;
  image?: T;
  imageCaption?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response_select".
 */
export interface ResponseSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  headingLight?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "response_card_select".
 */
export interface ResponseCardSelect<T extends boolean = true> {
  indexLabel?: T;
  title?: T;
  body?: T;
  bars?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles_select".
 */
export interface PrinciplesSelect<T extends boolean = true> {
  sectionLabel?: T;
  exploreHeading?: T;
  exploreBody?: T;
  exploreCtaLabel?: T;
  exploreCtaHref?: T;
  exploreBackgroundImage?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        bars?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standards_select".
 */
export interface StandardsSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  body?: T;
  cards?:
    | T
    | {
        slug?: T;
        title?: T;
        tagline?: T;
        image?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  headingStart?: T;
  headingMiddle?: T;
  headingEnd?: T;
  subheading?: T;
  buttonLabel?: T;
  buttonHref?: T;
  cards?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline: string;
  copyright: string;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  copyright?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}